# Generated by Django 3.1.4 on 2021-01-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('obs', models.CharField(max_length=250)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
            ],
            options={
                'verbose_name': 'Agendamentos',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['id'],
            },
        ),
    ]
