# Generated by Django 3.1.4 on 2021-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='obs',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
