# Generated by Django 3.1.4 on 2020-12-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
                ('rota', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['id'],
            },
        ),
    ]
