# Generated by Django 3.1.4 on 2020-12-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sites',
            new_name='Urls',
        ),
    ]
