# Generated by Django 3.1.4 on 2020-12-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201231_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='urls',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
