# Generated by Django 3.1.5 on 2021-01-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201231_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ['nome'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
