# Generated by Django 3.1.5 on 2021-01-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
       
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
