# Generated by Django 3.1.5 on 2021-01-07 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0002_auto_20210107_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=50)),
                ('especialidade', models.CharField(max_length=200)),
                ('telefone_residencial', models.CharField(blank=True, max_length=200)),
                ('telefone_celular', models.CharField(blank=True, max_length=100)),
                ('telefone_comercial', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=3)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('numero', models.IntegerField(blank=True)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedor',
                'ordering': ['id'],
            },
        ),
    ]
