# Generated by Django 3.1.4 on 2021-01-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0007_auto_20210109_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
