# Generated by Django 3.1.4 on 2021-01-09 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_auto_20210109_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=50)),
                ('ramo', models.CharField(max_length=200)),
                ('telefone_residencial', models.CharField(blank=True, max_length=200)),
                ('telefone_celular', models.CharField(blank=True, max_length=100)),
                ('telefone_comercial', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=3)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('numero', models.IntegerField(blank=True)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('obs', models.CharField(blank=True, max_length=200)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=100)),
                ('conta', models.CharField(blank=True, max_length=100)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Fornecedores',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=255)),
                ('un_medida', models.CharField(max_length=50)),
                ('qtd', models.IntegerField()),
                ('custo', models.FloatField()),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.fornecedores')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoque',
                'ordering': ['id'],
            },
        ),
    ]
