# Generated by Django 3.1.4 on 2021-01-09 22:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0009_estoque_fornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=255)),
                ('un_medida', models.CharField(max_length=50)),
                ('qtd', models.IntegerField()),
                ('custo', models.FloatField()),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.fornecedores')),
            ],
            options={
                'verbose_name': 'Produtos',
                'verbose_name_plural': 'Produtos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
