# Generated by Django 3.1.4 on 2021-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_auto_20210109_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='custo',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd',
            field=models.CharField(max_length=100),
        ),
    ]
