# Generated by Django 3.1.4 on 2021-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0011_auto_20210110_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='custo',
            field=models.CharField(max_length=100),
        ),
    ]
