# Generated by Django 3.1.4 on 2021-01-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0013_auto_20210110_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='qtd',
        ),
    ]
