# Generated by Django 3.1.4 on 2021-01-13 00:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0014_remove_produtos_qtd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.CharField(max_length=200)),
                ('custo', models.FloatField()),
                ('data_movimento', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos')),
            ],
            options={
                'verbose_name': 'Estoques',
                'verbose_name_plural': 'Estoques',
                'ordering': ['id'],
            },
        ),
    ]
