# Generated by Django 3.1.4 on 2021-01-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['id'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='custo',
            new_name='valor',
        ),
    ]
