# Generated by Django 3.1.5 on 2021-01-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0017_auto_20210113_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='venda',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
