# Generated by Django 3.1.5 on 2021-01-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0020_auto_20210121_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='pagamento',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
