# Generated by Django 3.1.5 on 2021-01-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0021_produtos_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='pagamento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
