# Generated by Django 3.1.5 on 2021-01-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0026_remove_estoque_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_total', models.CharField(max_length=200)),
                ('valor_total', models.FloatField()),
                ('pagamento', models.DateTimeField(blank=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos')),
            ],
            options={
                'verbose_name': 'Pagamentos',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['id'],
            },
        ),
    ]
