# Generated by Django 3.1.4 on 2021-01-24 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0029_auto_20210121_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustosFixos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('pagamento', models.CharField(blank=True, max_length=200)),
                ('custo', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Custos Fixos',
                'verbose_name_plural': 'Custos Fixos',
                'ordering': ['id'],
            },
        ),
    ]
