# Generated by Django 3.1.4 on 2021-01-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0030_custosfixos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentos',
            name='produto',
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='cod',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='nome',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
