# Generated by Django 3.1.4 on 2021-01-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0031_auto_20210124_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentos',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='pagamentos',
            name='nome',
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos'),
            preserve_default=False,
        ),
    ]
