# Generated by Django 3.1.5 on 2021-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0032_auto_20210124_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custosfixos',
            name='custo',
            field=models.FloatField(),
        ),
    ]
