# Generated by Django 3.1.4 on 2021-01-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0033_auto_20210127_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='custosfixos',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
