# Generated by Django 3.1.5 on 2021-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0034_custosfixos_recorrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custosfixos',
            name='recorrente',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
