# Generated by Django 3.1.4 on 2021-01-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=50)),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(max_length=100)),
                ('idade', models.CharField(blank=True, max_length=50)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('data_nascimento', models.CharField(blank=True, max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'Pacientes',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['id'],
            },
        ),
    ]
