# Generated by Django 3.1.4 on 2021-01-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_servicos'),
        ('pacientes', '0002_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='servico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrativo.servicos'),
            preserve_default=False,
        ),
    ]
