# Generated by Django 3.1.4 on 2021-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20210116_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='qtd_produto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='qtd_servico',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
