# Generated by Django 3.1.4 on 2021-01-16 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20210116_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
