# Generated by Django 3.1.4 on 2021-01-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20210116_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='cod_produto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='cod_servico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='produto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='qtd_produto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='qtd_servico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='servico',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_produto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_servico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
