# Generated by Django 3.1.4 on 2021-01-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_servicos'),
        ('pacientes', '0009_auto_20210116_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos'),
        ),
        migrations.AlterField(
            model_name='faturaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.servicos'),
        ),
    ]
