# Generated by Django 3.1.5 on 2021-01-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_servicos'),
        ('pacientes', '0012_fecharfatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fecharfatura',
            name='qtd_produto',
        ),
        migrations.RemoveField(
            model_name='fecharfatura',
            name='qtd_servico',
        ),
        migrations.RemoveField(
            model_name='fecharfatura',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='fecharfatura',
            name='valor_produto',
        ),
        migrations.RemoveField(
            model_name='fecharfatura',
            name='valor_servico',
        ),
        migrations.AddField(
            model_name='fecharfatura',
            name='produto_servico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrativo.servicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fecharfatura',
            name='qtd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fecharfatura',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fecharfatura',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
