# Generated by Django 3.1.5 on 2021-01-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('administrativo', '0019_servicos'),
        ('pacientes', '0013_auto_20210118_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FecharFatura',
            new_name='HistoricoFatura',
        ),
    ]
