# Generated by Django 3.1.5 on 2021-01-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_auto_20210118_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicofatura',
            options={'ordering': ['id'], 'verbose_name': 'Histórico Fatura', 'verbose_name_plural': 'Histórico Fatura'},
        ),
    ]
