# Generated by Django 3.1.5 on 2021-01-18 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('administrativo', '0019_servicos'),
        ('pacientes', '0016_delete_historicofatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
                ('produto_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.servicos')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'Histórico Fatura',
                'verbose_name_plural': 'Histórico Fatura',
                'ordering': ['id'],
            },
        ),
    ]
