# Generated by Django 3.1.5 on 2021-01-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_historicofatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturaproduto',
            name='cod_produto',
        ),
    ]
