# Generated by Django 3.1.5 on 2021-01-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_servicos'),
        ('pacientes', '0019_fatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicofatura',
            old_name='qtd',
            new_name='qtd_produto',
        ),
        migrations.RenameField(
            model_name='historicofatura',
            old_name='valor',
            new_name='qtd_servico',
        ),
        migrations.RenameField(
            model_name='historicofatura',
            old_name='produto_servico',
            new_name='servico',
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='valor_produto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicofatura',
            name='valor_servico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Fatura',
        ),
    ]
