# Generated by Django 3.1.5 on 2021-01-18 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0024_delete_historicofatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('tutor', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=200)),
                ('qtd_produto', models.FloatField(blank=True, null=True)),
                ('valor_produto', models.FloatField(blank=True, null=True)),
                ('servico', models.CharField(max_length=200)),
                ('qtd_servico', models.FloatField(blank=True, null=True)),
                ('valor_servico', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Histórico Fatura',
                'verbose_name_plural': 'Histórico Fatura',
                'ordering': ['id'],
            },
        ),
    ]
