# Generated by Django 3.1.5 on 2021-01-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_servicos'),
        ('clientes', '0001_initial'),
        ('pacientes', '0025_historicofatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicofatura',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.servicos'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
    ]
