# Generated by Django 3.1.4 on 2021-01-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_servicos'),
        ('pacientes', '0027_auto_20210118_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicofatura',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.produtos'),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.servicos'),
        ),
    ]
