# Generated by Django 3.1.5 on 2021-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0028_auto_20210118_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaproduto',
            name='faturado',
            field=models.CharField(default='NAO', max_length=50),
        ),
    ]
