# Generated by Django 3.1.5 on 2021-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0029_faturaproduto_faturado'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaservico',
            name='faturado',
            field=models.CharField(default='NAO', max_length=50),
        ),
    ]
