# Generated by Django 3.1.5 on 2021-01-19 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0032_auto_20210119_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturaservico',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
