# Generated by Django 3.1.5 on 2021-01-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0033_auto_20210119_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturaproduto',
            old_name='qtd_produto',
            new_name='qtd',
        ),
        migrations.RenameField(
            model_name='faturaproduto',
            old_name='valor_produto',
            new_name='valor',
        ),
        migrations.DeleteModel(
            name='FaturaServico',
        ),
    ]
