# Generated by Django 3.1.5 on 2021-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0034_auto_20210119_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaproduto',
            name='cod',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faturaproduto',
            name='faturado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faturaproduto',
            name='produto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
