# Generated by Django 3.1.5 on 2021-01-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0036_remove_faturaproduto_faturado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicofatura',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='historicofatura',
            name='qtd_produto',
        ),
        migrations.RemoveField(
            model_name='historicofatura',
            name='qtd_servico',
        ),
        migrations.RemoveField(
            model_name='historicofatura',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='historicofatura',
            name='valor_produto',
        ),
        migrations.RemoveField(
            model_name='historicofatura',
            name='valor_servico',
        ),
    ]
