# Generated by Django 3.1.4 on 2021-01-20 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0039_faturaproduto_faturado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturaproduto',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
