# Generated by Django 3.1.4 on 2021-01-20 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0040_auto_20210120_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturaproduto',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='historicofatura',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
