# Generated by Django 3.1.4 on 2021-01-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0041_auto_20210120_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaproduto',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
