# Generated by Django 3.1.4 on 2021-01-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0042_faturaproduto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofatura',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
