# Generated by Django 3.1.4 on 2021-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0043_historicofatura_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaVeterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('crmv', models.IntegerField()),
                ('uf', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Assinatura Veterinário',
                'verbose_name_plural': 'Assinatura Veterinário',
                'ordering': ['id'],
            },
        ),
    ]
