# Generated by Django 3.1.4 on 2021-01-23 01:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pacientes', '0044_assinaturaveterinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('data_cadastro', models.DateField(blank=True, default=datetime.datetime.today)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.assinaturaveterinario')),
            ],
            options={
                'verbose_name': 'Prescricao',
                'verbose_name_plural': 'Prescricao',
                'ordering': ['id'],
            },
        ),
    ]
