# Generated by Django 3.1.4 on 2021-01-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0045_prescricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
